- hosts: all
  sudo: True
  user: vagrant
  tasks:
    - name: Install the nginx packages
      yum: name=nginx state=present
      with_items: redhat_pkg
      when: ansible_os_family == "RedHat"

    - name: Install the nginx packages
      apt: name=nginx state=present update_cache=yes
      with_items: ubuntu_pkg
      when: ansible_os_family == "Debian"
